sospechosos = [
    "Juan Pérez", "María Rodríguez", "Carlos Sánchez", "Ana Gómez", "Luis Ramírez", "Sofía Herrera", "Pedro Jiménez", "Laura Castro", "Miguel Torres", "Carmen Díaz",
    "Ricardo Morales", "Elena Vargas", "Javier Navarro", "Patricia Suárez", "Gustavo Blanco", "Verónica Méndez", "Martín Silva", "Lucía Rojas", "Fernando Ibarra", "Silvia Ortega",
    "Hugo Figueroa", "Andrea Cabrera", "Diego Pérez", "Valeria Fuentes", "Emiliano Soto", "Rosa Martínez", "Guillermo Peralta", "Natalia Medina", "Oscar Domínguez", "Daniela Guzmán",
    "Alberto Salazar", "Monica Estrada", "Francisco León", "Gabriela Núñez", "Raúl Espinoza", "Beatriz Valencia", "Rodrigo Castaño", "Camila Soto", "Sebastián Aguirre", "Paula Araya",
    "Matías Paredes", "Adriana Flores", "Ignacio Cortés", "Esteban Ruiz", "Florencia Godoy", "Cristian Orozco", "Juliana Peña", "Federico Miranda", "Gloria Sandoval", "Héctor Farias"
]

muestras = [
    "CGGGGCTAAAATTTTTTACGATCGGCGTTAGCTAGCTAGCGATGCGTACGTTAGCTAGC", 
    "AACGTTTAATGTTCTAAGCTGCGAGCTAGTACGTTAGCGTATCGTACGATCGTATGCTACG", 
    "CGGGGCTAAAATTTTTTACGATCGTATCGTAGCTGATCGTACGTAGCTAGCTAGCTACGTG",
    "ATGCTAGCTGCTAGCTGCTGATGCTAGCTGCTAGCTAGTCGATCGTAGCTAGCTAGCTAGC",
    "GCTAGCTGATCGTACGTAGCTGCTAGCTGCTAGCTGCTAGTAGCTAGTGCAGTGCAGTAGC",
    "TGCATGCTAGCTGATCGTAGCTAGCTAGCTGCTAGCTGCTAGCTGCTAGCTGCTGATGCAT",
    "CGATCGTAGCTGATCGTACGTAGCTAGCTGCTGCTAGCTAGCTAGCTGCTGATCGTACGTG",
    "AGCTGATCGTACGTAGCTAGCTGCTAGCTGCTGCTGCTAGCTGCTAGCTAGCTAGCTAGCT",
    "GATCGTAGCTGATCGTACGTAGCTGCTAGCTGCTGCTGCTAGCTAGCTAGCTAGCTAGCTA",
    "TAGCTGATCGTACGTAGCTAGCTGCTAGCTGCTAGCTGCTAGCTAGCTAGCTAGCTAGCTA",
    "CTGATCGTAGCTGATCGTACGTAGCTAGCTGCTGCTAGCTGCTAGCTGCTAGCTAGCTAGC",
    "GATCGTAGCTGATCGTACGTAGCTAGCTGCTAGCTGCTAGCTGCTAGCTAGCTAGCTAGCT",
    "ATCGTAGCTGATCGTACGTAGCTGCTAGCTGCTGCTAGCTAGCTAGCTAGCTAGCTAGCTA",
    "GCTAGCTGATCGTACGTAGCTAGCTGCTAGCTGCTAGCTGCTAGCTAGCTAGCTAGCTAGC",
    "TACGTAGCTGATCGTACGTAGCTAGCTGCTAGCTGCTAGCTGCTAGCTAGCTAGCTAGCTA",
    "CGTACGTAGCTGATCGTACGTAGCTAGCTGCTAGCTGCTAGCTGCTAGCTAGCTAGCTAGC",
    "GCTAGCTGATCGTACGTAGCTAGCTGCTAGCTGCTAGCTGCTAGCTAGCTAGCTAGCTAGC",
    "ATGCTAGCTGCTAGCTGCTGATGCTAGCTGCTAGCTAGTCGATCGTAGCTAGCTAGCTAGC",
    "AGCTAGCTAGCTGATCGTAGCTGCTAGCTGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTA",
    "CTAGCTGATCGTACGTAGCTAGCTGCTAGCTGCTAGCTGCTAGCTAGCTAGCTAGCTAGCT"
]